// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/v3/model.proto

package common

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AgoraData_TransactionType int32

const (
	AgoraData_UNKNOWN AgoraData_TransactionType = 0
	AgoraData_EARN    AgoraData_TransactionType = 1
	AgoraData_SPEND   AgoraData_TransactionType = 2
	AgoraData_P2P     AgoraData_TransactionType = 3
)

var AgoraData_TransactionType_name = map[int32]string{
	0: "UNKNOWN",
	1: "EARN",
	2: "SPEND",
	3: "P2P",
}

var AgoraData_TransactionType_value = map[string]int32{
	"UNKNOWN": 0,
	"EARN":    1,
	"SPEND":   2,
	"P2P":     3,
}

func (x AgoraData_TransactionType) String() string {
	return proto.EnumName(AgoraData_TransactionType_name, int32(x))
}

func (AgoraData_TransactionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ab58ade4bb87a1ff, []int{4, 0}
}

type StellarAccountId struct {
	// The public key of accounts always starts with a G, so we
	// ensure that the value starts with a G to prevent the secret
	// key from being used.
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StellarAccountId) Reset()         { *m = StellarAccountId{} }
func (m *StellarAccountId) String() string { return proto.CompactTextString(m) }
func (*StellarAccountId) ProtoMessage()    {}
func (*StellarAccountId) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab58ade4bb87a1ff, []int{0}
}

func (m *StellarAccountId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StellarAccountId.Unmarshal(m, b)
}
func (m *StellarAccountId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StellarAccountId.Marshal(b, m, deterministic)
}
func (m *StellarAccountId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StellarAccountId.Merge(m, src)
}
func (m *StellarAccountId) XXX_Size() int {
	return xxx_messageInfo_StellarAccountId.Size(m)
}
func (m *StellarAccountId) XXX_DiscardUnknown() {
	xxx_messageInfo_StellarAccountId.DiscardUnknown(m)
}

var xxx_messageInfo_StellarAccountId proto.InternalMessageInfo

func (m *StellarAccountId) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type TransactionHash struct {
	// The sha256 hash of a transaction.
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionHash) Reset()         { *m = TransactionHash{} }
func (m *TransactionHash) String() string { return proto.CompactTextString(m) }
func (*TransactionHash) ProtoMessage()    {}
func (*TransactionHash) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab58ade4bb87a1ff, []int{1}
}

func (m *TransactionHash) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionHash.Unmarshal(m, b)
}
func (m *TransactionHash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionHash.Marshal(b, m, deterministic)
}
func (m *TransactionHash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionHash.Merge(m, src)
}
func (m *TransactionHash) XXX_Size() int {
	return xxx_messageInfo_TransactionHash.Size(m)
}
func (m *TransactionHash) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionHash.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionHash proto.InternalMessageInfo

func (m *TransactionHash) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type BigDecimal struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BigDecimal) Reset()         { *m = BigDecimal{} }
func (m *BigDecimal) String() string { return proto.CompactTextString(m) }
func (*BigDecimal) ProtoMessage()    {}
func (*BigDecimal) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab58ade4bb87a1ff, []int{2}
}

func (m *BigDecimal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BigDecimal.Unmarshal(m, b)
}
func (m *BigDecimal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BigDecimal.Marshal(b, m, deterministic)
}
func (m *BigDecimal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BigDecimal.Merge(m, src)
}
func (m *BigDecimal) XXX_Size() int {
	return xxx_messageInfo_BigDecimal.Size(m)
}
func (m *BigDecimal) XXX_DiscardUnknown() {
	xxx_messageInfo_BigDecimal.DiscardUnknown(m)
}

var xxx_messageInfo_BigDecimal proto.InternalMessageInfo

func (m *BigDecimal) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type AgoraDataUrl struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgoraDataUrl) Reset()         { *m = AgoraDataUrl{} }
func (m *AgoraDataUrl) String() string { return proto.CompactTextString(m) }
func (*AgoraDataUrl) ProtoMessage()    {}
func (*AgoraDataUrl) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab58ade4bb87a1ff, []int{3}
}

func (m *AgoraDataUrl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgoraDataUrl.Unmarshal(m, b)
}
func (m *AgoraDataUrl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgoraDataUrl.Marshal(b, m, deterministic)
}
func (m *AgoraDataUrl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgoraDataUrl.Merge(m, src)
}
func (m *AgoraDataUrl) XXX_Size() int {
	return xxx_messageInfo_AgoraDataUrl.Size(m)
}
func (m *AgoraDataUrl) XXX_DiscardUnknown() {
	xxx_messageInfo_AgoraDataUrl.DiscardUnknown(m)
}

var xxx_messageInfo_AgoraDataUrl proto.InternalMessageInfo

func (m *AgoraDataUrl) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type AgoraData struct {
	// A renderable title related to the transaction.
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// A renderable description related to the transaction.
	Description     string                    `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	TransactionType AgoraData_TransactionType `protobuf:"varint,3,opt,name=transaction_type,json=transactionType,proto3,enum=kin.common.v3.AgoraData_TransactionType" json:"transaction_type,omitempty"`
	// The total amount, in quarks, of the 'item(s)' the transaction
	// was related to. This should be the same as the transaction
	// amount. If there is a mismatch, then the client mis-used or
	// abused the memo system, likely by circumventing the Agora
	// services.
	TotalAmount int64 `protobuf:"varint,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	// The full foreign key of the off-chain data, which is
	// prefixed in the memo. This can be treated similar SKU.
	ForeignKey []byte `protobuf:"bytes,5,opt,name=foreign_key,json=foreignKey,proto3" json:"foreign_key,omitempty"`
	// The invoice related to the transaction, if the service was
	// able to resolve one using the foreign key.
	Invoice              *Invoice `protobuf:"bytes,6,opt,name=invoice,proto3" json:"invoice,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgoraData) Reset()         { *m = AgoraData{} }
func (m *AgoraData) String() string { return proto.CompactTextString(m) }
func (*AgoraData) ProtoMessage()    {}
func (*AgoraData) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab58ade4bb87a1ff, []int{4}
}

func (m *AgoraData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgoraData.Unmarshal(m, b)
}
func (m *AgoraData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgoraData.Marshal(b, m, deterministic)
}
func (m *AgoraData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgoraData.Merge(m, src)
}
func (m *AgoraData) XXX_Size() int {
	return xxx_messageInfo_AgoraData.Size(m)
}
func (m *AgoraData) XXX_DiscardUnknown() {
	xxx_messageInfo_AgoraData.DiscardUnknown(m)
}

var xxx_messageInfo_AgoraData proto.InternalMessageInfo

func (m *AgoraData) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *AgoraData) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AgoraData) GetTransactionType() AgoraData_TransactionType {
	if m != nil {
		return m.TransactionType
	}
	return AgoraData_UNKNOWN
}

func (m *AgoraData) GetTotalAmount() int64 {
	if m != nil {
		return m.TotalAmount
	}
	return 0
}

func (m *AgoraData) GetForeignKey() []byte {
	if m != nil {
		return m.ForeignKey
	}
	return nil
}

func (m *AgoraData) GetInvoice() *Invoice {
	if m != nil {
		return m.Invoice
	}
	return nil
}

type InvoiceHash struct {
	// The SHA-224 hash of the invoice.
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvoiceHash) Reset()         { *m = InvoiceHash{} }
func (m *InvoiceHash) String() string { return proto.CompactTextString(m) }
func (*InvoiceHash) ProtoMessage()    {}
func (*InvoiceHash) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab58ade4bb87a1ff, []int{5}
}

func (m *InvoiceHash) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvoiceHash.Unmarshal(m, b)
}
func (m *InvoiceHash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvoiceHash.Marshal(b, m, deterministic)
}
func (m *InvoiceHash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvoiceHash.Merge(m, src)
}
func (m *InvoiceHash) XXX_Size() int {
	return xxx_messageInfo_InvoiceHash.Size(m)
}
func (m *InvoiceHash) XXX_DiscardUnknown() {
	xxx_messageInfo_InvoiceHash.DiscardUnknown(m)
}

var xxx_messageInfo_InvoiceHash proto.InternalMessageInfo

func (m *InvoiceHash) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type Invoice struct {
	Items                []*Invoice_LineItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Nonce                *Nonce              `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Invoice) Reset()         { *m = Invoice{} }
func (m *Invoice) String() string { return proto.CompactTextString(m) }
func (*Invoice) ProtoMessage()    {}
func (*Invoice) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab58ade4bb87a1ff, []int{6}
}

func (m *Invoice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Invoice.Unmarshal(m, b)
}
func (m *Invoice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Invoice.Marshal(b, m, deterministic)
}
func (m *Invoice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Invoice.Merge(m, src)
}
func (m *Invoice) XXX_Size() int {
	return xxx_messageInfo_Invoice.Size(m)
}
func (m *Invoice) XXX_DiscardUnknown() {
	xxx_messageInfo_Invoice.DiscardUnknown(m)
}

var xxx_messageInfo_Invoice proto.InternalMessageInfo

func (m *Invoice) GetItems() []*Invoice_LineItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *Invoice) GetNonce() *Nonce {
	if m != nil {
		return m.Nonce
	}
	return nil
}

type Invoice_LineItem struct {
	Title       string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// The amount in quarks.
	Amount int64 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	// The app SKU related to this line item, if applicable.
	Sku                  []byte   `protobuf:"bytes,4,opt,name=sku,proto3" json:"sku,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Invoice_LineItem) Reset()         { *m = Invoice_LineItem{} }
func (m *Invoice_LineItem) String() string { return proto.CompactTextString(m) }
func (*Invoice_LineItem) ProtoMessage()    {}
func (*Invoice_LineItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab58ade4bb87a1ff, []int{6, 0}
}

func (m *Invoice_LineItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Invoice_LineItem.Unmarshal(m, b)
}
func (m *Invoice_LineItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Invoice_LineItem.Marshal(b, m, deterministic)
}
func (m *Invoice_LineItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Invoice_LineItem.Merge(m, src)
}
func (m *Invoice_LineItem) XXX_Size() int {
	return xxx_messageInfo_Invoice_LineItem.Size(m)
}
func (m *Invoice_LineItem) XXX_DiscardUnknown() {
	xxx_messageInfo_Invoice_LineItem.DiscardUnknown(m)
}

var xxx_messageInfo_Invoice_LineItem proto.InternalMessageInfo

func (m *Invoice_LineItem) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Invoice_LineItem) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Invoice_LineItem) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Invoice_LineItem) GetSku() []byte {
	if m != nil {
		return m.Sku
	}
	return nil
}

type Nonce struct {
	// The time the nonce was generated.
	//
	// If the generation time value is too far in the past _or_ future of the service time,
	// the nonce will be rejected.
	GenerationTime *timestamp.Timestamp `protobuf:"bytes,1,opt,name=generation_time,json=generationTime,proto3" json:"generation_time,omitempty"`
	// A random value.
	Value                int64    `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nonce) Reset()         { *m = Nonce{} }
func (m *Nonce) String() string { return proto.CompactTextString(m) }
func (*Nonce) ProtoMessage()    {}
func (*Nonce) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab58ade4bb87a1ff, []int{7}
}

func (m *Nonce) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nonce.Unmarshal(m, b)
}
func (m *Nonce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nonce.Marshal(b, m, deterministic)
}
func (m *Nonce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nonce.Merge(m, src)
}
func (m *Nonce) XXX_Size() int {
	return xxx_messageInfo_Nonce.Size(m)
}
func (m *Nonce) XXX_DiscardUnknown() {
	xxx_messageInfo_Nonce.DiscardUnknown(m)
}

var xxx_messageInfo_Nonce proto.InternalMessageInfo

func (m *Nonce) GetGenerationTime() *timestamp.Timestamp {
	if m != nil {
		return m.GenerationTime
	}
	return nil
}

func (m *Nonce) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterEnum("kin.common.v3.AgoraData_TransactionType", AgoraData_TransactionType_name, AgoraData_TransactionType_value)
	proto.RegisterType((*StellarAccountId)(nil), "kin.common.v3.StellarAccountId")
	proto.RegisterType((*TransactionHash)(nil), "kin.common.v3.TransactionHash")
	proto.RegisterType((*BigDecimal)(nil), "kin.common.v3.BigDecimal")
	proto.RegisterType((*AgoraDataUrl)(nil), "kin.common.v3.AgoraDataUrl")
	proto.RegisterType((*AgoraData)(nil), "kin.common.v3.AgoraData")
	proto.RegisterType((*InvoiceHash)(nil), "kin.common.v3.InvoiceHash")
	proto.RegisterType((*Invoice)(nil), "kin.common.v3.Invoice")
	proto.RegisterType((*Invoice_LineItem)(nil), "kin.common.v3.Invoice.LineItem")
	proto.RegisterType((*Nonce)(nil), "kin.common.v3.Nonce")
}

func init() { proto.RegisterFile("common/v3/model.proto", fileDescriptor_ab58ade4bb87a1ff) }

var fileDescriptor_ab58ade4bb87a1ff = []byte{
	// 719 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x5d, 0x6b, 0xe3, 0x46,
	0x14, 0xdd, 0x91, 0x22, 0x5b, 0x1e, 0xa5, 0x6b, 0x31, 0x6c, 0x76, 0x85, 0x59, 0x88, 0x6a, 0xfa,
	0xa0, 0x94, 0xb5, 0x64, 0xcb, 0x4b, 0xd9, 0x6c, 0x0b, 0xc1, 0xc2, 0xa1, 0x0d, 0x49, 0xdd, 0xa0,
	0x24, 0x14, 0x92, 0x26, 0x61, 0x22, 0x4f, 0x94, 0xc1, 0x92, 0xc6, 0x48, 0x63, 0x83, 0xd3, 0x06,
	0xf2, 0xdc, 0x87, 0x3e, 0x94, 0xfe, 0x92, 0xfe, 0xb0, 0xfe, 0x00, 0x3f, 0x15, 0x8d, 0x2c, 0xc7,
	0x4e, 0x3f, 0xd8, 0x37, 0xdd, 0x7b, 0xce, 0xbd, 0x73, 0x74, 0xcf, 0xe5, 0xc2, 0xad, 0x80, 0xc5,
	0x31, 0x4b, 0x9c, 0x69, 0xd7, 0x89, 0xd9, 0x90, 0x44, 0xf6, 0x38, 0x65, 0x9c, 0xa1, 0xcf, 0x46,
	0x34, 0xb1, 0x0b, 0xc8, 0x9e, 0x76, 0x1b, 0x6f, 0xa6, 0x38, 0xa2, 0x43, 0xcc, 0x89, 0x53, 0x7e,
	0x14, 0xbc, 0xc6, 0x76, 0xc8, 0x58, 0x18, 0x11, 0x47, 0x44, 0x37, 0x93, 0x5b, 0x87, 0xd3, 0x98,
	0x64, 0x1c, 0xc7, 0xe3, 0x82, 0xd0, 0xec, 0x43, 0xfd, 0x84, 0x93, 0x28, 0xc2, 0x69, 0x2f, 0x08,
	0xd8, 0x24, 0xe1, 0x07, 0x43, 0xd4, 0x86, 0xca, 0x14, 0x47, 0x13, 0x62, 0x00, 0x13, 0x58, 0x35,
	0xaf, 0x31, 0xf7, 0xde, 0xa4, 0x5b, 0xe6, 0x07, 0xeb, 0x83, 0x5b, 0xbf, 0xfa, 0xf6, 0x02, 0xb7,
	0xee, 0x7b, 0xad, 0xf3, 0x76, 0x6b, 0xf7, 0xf2, 0xcb, 0x2f, 0xfc, 0x82, 0xd8, 0x74, 0x61, 0xfd,
	0x34, 0xc5, 0x49, 0x86, 0x03, 0x4e, 0x59, 0xf2, 0x1d, 0xce, 0xee, 0xd0, 0xf6, 0x6a, 0x93, 0x4d,
	0xaf, 0x36, 0xf7, 0x2a, 0xf7, 0x1b, 0xba, 0x69, 0x98, 0x65, 0xcd, 0x39, 0x84, 0x1e, 0x0d, 0xfb,
	0x24, 0xa0, 0x31, 0x8e, 0xd0, 0xd1, 0xfa, 0x9b, 0x5f, 0xcd, 0xbd, 0x6e, 0xda, 0x71, 0x9d, 0x2b,
	0x6b, 0xef, 0xe3, 0x45, 0xa7, 0xb5, 0x7b, 0x79, 0x91, 0x3f, 0xf8, 0x73, 0xfb, 0x5d, 0xe7, 0xfd,
	0xc3, 0x2f, 0xed, 0x1d, 0x6b, 0xef, 0xe3, 0x4f, 0xf6, 0x32, 0xd5, 0x79, 0x10, 0x94, 0x9d, 0xbd,
	0xa5, 0x9e, 0x36, 0xdc, 0xec, 0x85, 0x2c, 0xc5, 0x7d, 0xcc, 0xf1, 0x59, 0x1a, 0x21, 0x73, 0xbd,
	0x3b, 0x9c, 0x7b, 0xd5, 0x54, 0xd1, 0x81, 0xf1, 0xa8, 0x97, 0x15, 0x7f, 0x49, 0xb0, 0xb6, 0x2c,
	0xc9, 0xf9, 0x9c, 0xf2, 0xe8, 0x9f, 0x7c, 0xc9, 0x2f, 0x00, 0xf4, 0x0e, 0x6a, 0x43, 0x92, 0x05,
	0x29, 0x1d, 0xe7, 0x7f, 0x6c, 0x48, 0xcf, 0x78, 0xaa, 0xbf, 0x0a, 0xa3, 0x13, 0xa8, 0xf3, 0xa7,
	0xf9, 0x5c, 0xf3, 0xd9, 0x98, 0x18, 0xb2, 0x09, 0xac, 0x97, 0xae, 0x65, 0xaf, 0x39, 0x69, 0x2f,
	0x35, 0xd8, 0x2b, 0x03, 0x3d, 0x9d, 0x8d, 0x89, 0x5f, 0xe7, 0xeb, 0x09, 0xf4, 0x39, 0xdc, 0xe4,
	0x8c, 0xe3, 0xe8, 0x1a, 0xc7, 0xb9, 0x71, 0xc6, 0x86, 0x09, 0x2c, 0xd9, 0xd7, 0x44, 0xae, 0x27,
	0x52, 0x68, 0x07, 0x6a, 0xb7, 0x2c, 0x25, 0x34, 0x4c, 0xae, 0x47, 0x64, 0x66, 0x28, 0xc2, 0x0a,
	0x75, 0xee, 0x29, 0xf7, 0x72, 0xfe, 0x2f, 0x70, 0x01, 0x1e, 0x92, 0x19, 0x6a, 0xc3, 0x2a, 0x4d,
	0xa6, 0x8c, 0x06, 0xc4, 0xa8, 0x98, 0xc0, 0xd2, 0xdc, 0xd7, 0xcf, 0x94, 0x1d, 0x14, 0xa8, 0x5f,
	0xd2, 0x9a, 0xdf, 0xac, 0x99, 0x2e, 0x24, 0x69, 0xb0, 0x7a, 0x36, 0x38, 0x1c, 0xfc, 0xf0, 0xe3,
	0x40, 0x7f, 0x81, 0x54, 0xb8, 0xb1, 0xdf, 0xf3, 0x07, 0x3a, 0x40, 0x35, 0xa8, 0x9c, 0x1c, 0xef,
	0x0f, 0xfa, 0xba, 0x84, 0xaa, 0x50, 0x3e, 0x76, 0x8f, 0x75, 0xb9, 0x69, 0x43, 0x6d, 0xd1, 0xf1,
	0x7f, 0xd6, 0xe5, 0xad, 0xf1, 0xb6, 0x34, 0xe8, 0x0f, 0x09, 0x56, 0x17, 0x05, 0xc8, 0x83, 0x0a,
	0xe5, 0x24, 0xce, 0x0c, 0x60, 0xca, 0x96, 0xe6, 0x6e, 0xff, 0xbb, 0x52, 0xfb, 0x88, 0x26, 0xe4,
	0x80, 0x93, 0xd8, 0xd3, 0xe6, 0x9e, 0xfa, 0x3b, 0x50, 0x54, 0xa0, 0x3f, 0xaa, 0x7e, 0x51, 0x8a,
	0xde, 0x43, 0x25, 0x61, 0x49, 0x40, 0x84, 0x75, 0x9a, 0xfb, 0xea, 0x59, 0x8f, 0x41, 0x8e, 0x89,
	0x51, 0xfd, 0x0a, 0x24, 0x1d, 0xf8, 0x05, 0xb9, 0xf1, 0x1b, 0x80, 0x6a, 0xd9, 0xf6, 0xbf, 0xb7,
	0x04, 0x7c, 0xca, 0x96, 0xbc, 0xc8, 0x1d, 0x58, 0xdb, 0x92, 0xd7, 0xb0, 0xb2, 0xb0, 0x52, 0x16,
	0x56, 0x2e, 0x22, 0xd4, 0x80, 0x72, 0x36, 0x9a, 0x08, 0x7f, 0x9f, 0xdc, 0x03, 0x7e, 0x9e, 0x6c,
	0x46, 0x50, 0x11, 0x52, 0xd1, 0xf7, 0xb0, 0x1e, 0x92, 0x84, 0xa4, 0xb8, 0xd8, 0x30, 0x1a, 0x17,
	0xb2, 0x34, 0xb7, 0x61, 0x17, 0x37, 0xc0, 0x2e, 0x6f, 0x80, 0x7d, 0x5a, 0xde, 0x00, 0xd1, 0xec,
	0x4f, 0x20, 0xa9, 0xc0, 0x7f, 0xf9, 0x54, 0x9c, 0xc3, 0xe8, 0x55, 0xe9, 0x87, 0x24, 0xa4, 0x14,
	0x81, 0xe7, 0xc3, 0x2d, 0x96, 0x86, 0x62, 0x54, 0x21, 0x59, 0x19, 0xd7, 0xf9, 0x6e, 0x48, 0xf9,
	0xdd, 0xe4, 0x26, 0xcf, 0x38, 0x23, 0x9a, 0x90, 0x80, 0x65, 0xb3, 0x8c, 0x13, 0x11, 0xb4, 0xf0,
	0x98, 0x3a, 0x21, 0x49, 0xc4, 0xfb, 0xce, 0xf2, 0x9e, 0x7d, 0x5d, 0x7c, 0xdd, 0x54, 0x44, 0xbe,
	0xfb, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xca, 0x62, 0xd3, 0x30, 0xea, 0x04, 0x00, 0x00,
}
