// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/v3/model.proto

package common

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StellarAccountId struct {
	// The public key of accounts always starts with a G, so we
	// ensure that the value starts with a G to prevent the secret
	// key from being used.
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StellarAccountId) Reset()         { *m = StellarAccountId{} }
func (m *StellarAccountId) String() string { return proto.CompactTextString(m) }
func (*StellarAccountId) ProtoMessage()    {}
func (*StellarAccountId) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab58ade4bb87a1ff, []int{0}
}

func (m *StellarAccountId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StellarAccountId.Unmarshal(m, b)
}
func (m *StellarAccountId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StellarAccountId.Marshal(b, m, deterministic)
}
func (m *StellarAccountId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StellarAccountId.Merge(m, src)
}
func (m *StellarAccountId) XXX_Size() int {
	return xxx_messageInfo_StellarAccountId.Size(m)
}
func (m *StellarAccountId) XXX_DiscardUnknown() {
	xxx_messageInfo_StellarAccountId.DiscardUnknown(m)
}

var xxx_messageInfo_StellarAccountId proto.InternalMessageInfo

func (m *StellarAccountId) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type TransactionHash struct {
	// The sha256 hash of a transaction.
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionHash) Reset()         { *m = TransactionHash{} }
func (m *TransactionHash) String() string { return proto.CompactTextString(m) }
func (*TransactionHash) ProtoMessage()    {}
func (*TransactionHash) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab58ade4bb87a1ff, []int{1}
}

func (m *TransactionHash) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionHash.Unmarshal(m, b)
}
func (m *TransactionHash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionHash.Marshal(b, m, deterministic)
}
func (m *TransactionHash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionHash.Merge(m, src)
}
func (m *TransactionHash) XXX_Size() int {
	return xxx_messageInfo_TransactionHash.Size(m)
}
func (m *TransactionHash) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionHash.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionHash proto.InternalMessageInfo

func (m *TransactionHash) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type InvoiceHash struct {
	// The SHA-224 hash of the invoice.
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvoiceHash) Reset()         { *m = InvoiceHash{} }
func (m *InvoiceHash) String() string { return proto.CompactTextString(m) }
func (*InvoiceHash) ProtoMessage()    {}
func (*InvoiceHash) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab58ade4bb87a1ff, []int{2}
}

func (m *InvoiceHash) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvoiceHash.Unmarshal(m, b)
}
func (m *InvoiceHash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvoiceHash.Marshal(b, m, deterministic)
}
func (m *InvoiceHash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvoiceHash.Merge(m, src)
}
func (m *InvoiceHash) XXX_Size() int {
	return xxx_messageInfo_InvoiceHash.Size(m)
}
func (m *InvoiceHash) XXX_DiscardUnknown() {
	xxx_messageInfo_InvoiceHash.DiscardUnknown(m)
}

var xxx_messageInfo_InvoiceHash proto.InternalMessageInfo

func (m *InvoiceHash) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type Invoice struct {
	Items                []*Invoice_LineItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Invoice) Reset()         { *m = Invoice{} }
func (m *Invoice) String() string { return proto.CompactTextString(m) }
func (*Invoice) ProtoMessage()    {}
func (*Invoice) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab58ade4bb87a1ff, []int{3}
}

func (m *Invoice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Invoice.Unmarshal(m, b)
}
func (m *Invoice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Invoice.Marshal(b, m, deterministic)
}
func (m *Invoice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Invoice.Merge(m, src)
}
func (m *Invoice) XXX_Size() int {
	return xxx_messageInfo_Invoice.Size(m)
}
func (m *Invoice) XXX_DiscardUnknown() {
	xxx_messageInfo_Invoice.DiscardUnknown(m)
}

var xxx_messageInfo_Invoice proto.InternalMessageInfo

func (m *Invoice) GetItems() []*Invoice_LineItem {
	if m != nil {
		return m.Items
	}
	return nil
}

type Invoice_LineItem struct {
	Title       string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// The amount in quarks.
	Amount int64 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	// The app SKU related to this line item, if applicable.
	Sku                  []byte   `protobuf:"bytes,4,opt,name=sku,proto3" json:"sku,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Invoice_LineItem) Reset()         { *m = Invoice_LineItem{} }
func (m *Invoice_LineItem) String() string { return proto.CompactTextString(m) }
func (*Invoice_LineItem) ProtoMessage()    {}
func (*Invoice_LineItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab58ade4bb87a1ff, []int{3, 0}
}

func (m *Invoice_LineItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Invoice_LineItem.Unmarshal(m, b)
}
func (m *Invoice_LineItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Invoice_LineItem.Marshal(b, m, deterministic)
}
func (m *Invoice_LineItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Invoice_LineItem.Merge(m, src)
}
func (m *Invoice_LineItem) XXX_Size() int {
	return xxx_messageInfo_Invoice_LineItem.Size(m)
}
func (m *Invoice_LineItem) XXX_DiscardUnknown() {
	xxx_messageInfo_Invoice_LineItem.DiscardUnknown(m)
}

var xxx_messageInfo_Invoice_LineItem proto.InternalMessageInfo

func (m *Invoice_LineItem) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Invoice_LineItem) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Invoice_LineItem) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Invoice_LineItem) GetSku() []byte {
	if m != nil {
		return m.Sku
	}
	return nil
}

type InvoiceList struct {
	Invoices             []*Invoice `protobuf:"bytes,1,rep,name=invoices,proto3" json:"invoices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *InvoiceList) Reset()         { *m = InvoiceList{} }
func (m *InvoiceList) String() string { return proto.CompactTextString(m) }
func (*InvoiceList) ProtoMessage()    {}
func (*InvoiceList) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab58ade4bb87a1ff, []int{4}
}

func (m *InvoiceList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvoiceList.Unmarshal(m, b)
}
func (m *InvoiceList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvoiceList.Marshal(b, m, deterministic)
}
func (m *InvoiceList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvoiceList.Merge(m, src)
}
func (m *InvoiceList) XXX_Size() int {
	return xxx_messageInfo_InvoiceList.Size(m)
}
func (m *InvoiceList) XXX_DiscardUnknown() {
	xxx_messageInfo_InvoiceList.DiscardUnknown(m)
}

var xxx_messageInfo_InvoiceList proto.InternalMessageInfo

func (m *InvoiceList) GetInvoices() []*Invoice {
	if m != nil {
		return m.Invoices
	}
	return nil
}

func init() {
	proto.RegisterType((*StellarAccountId)(nil), "kin.agora.common.v3.StellarAccountId")
	proto.RegisterType((*TransactionHash)(nil), "kin.agora.common.v3.TransactionHash")
	proto.RegisterType((*InvoiceHash)(nil), "kin.agora.common.v3.InvoiceHash")
	proto.RegisterType((*Invoice)(nil), "kin.agora.common.v3.Invoice")
	proto.RegisterType((*Invoice_LineItem)(nil), "kin.agora.common.v3.Invoice.LineItem")
	proto.RegisterType((*InvoiceList)(nil), "kin.agora.common.v3.InvoiceList")
}

func init() { proto.RegisterFile("common/v3/model.proto", fileDescriptor_ab58ade4bb87a1ff) }

var fileDescriptor_ab58ade4bb87a1ff = []byte{
	// 436 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x41, 0x6b, 0xdb, 0x30,
	0x14, 0xc7, 0xa7, 0x38, 0x4e, 0x5d, 0x79, 0x50, 0xa3, 0x51, 0x2a, 0xbc, 0xc0, 0x4c, 0xd8, 0x20,
	0x8c, 0xc5, 0x0e, 0xc9, 0xa5, 0xa3, 0xa7, 0x68, 0x85, 0x35, 0xd0, 0xc3, 0x70, 0xc7, 0x0e, 0x1d,
	0x1b, 0xa8, 0xb6, 0x70, 0x44, 0x6c, 0x29, 0x58, 0x8a, 0x61, 0x39, 0xe5, 0x33, 0xe4, 0x23, 0xec,
	0xd3, 0xed, 0x33, 0xf8, 0x34, 0x6c, 0xc7, 0x99, 0x0f, 0xa3, 0xb7, 0xe7, 0xff, 0xfb, 0xfd, 0x9f,
	0xf5, 0x7f, 0x3c, 0x78, 0x19, 0xc9, 0x2c, 0x93, 0x22, 0x28, 0xe6, 0x41, 0x26, 0x63, 0x96, 0xfa,
	0x9b, 0x5c, 0x6a, 0x89, 0x5e, 0xad, 0xb9, 0xf0, 0x69, 0x22, 0x73, 0xea, 0x37, 0x80, 0x5f, 0xcc,
	0xdd, 0xab, 0x82, 0xa6, 0x3c, 0xa6, 0x9a, 0x05, 0x6d, 0xd1, 0xd0, 0xa3, 0x5b, 0xe8, 0x3c, 0x68,
	0x96, 0xa6, 0x34, 0x5f, 0x44, 0x91, 0xdc, 0x0a, 0xbd, 0x8c, 0xd1, 0x14, 0x9a, 0x05, 0x4d, 0xb7,
	0x0c, 0x03, 0x0f, 0x8c, 0xcf, 0x89, 0x5b, 0x92, 0xab, 0xfc, 0xd2, 0xbb, 0x1e, 0x5f, 0xcf, 0x2e,
	0x7e, 0x7e, 0xfe, 0x4e, 0x27, 0xbb, 0xc5, 0xe4, 0x71, 0x3a, 0xf9, 0xf8, 0xe3, 0xfd, 0xdb, 0xb0,
	0x01, 0x47, 0x33, 0x78, 0xf1, 0x35, 0xa7, 0x42, 0xd1, 0x48, 0x73, 0x29, 0xee, 0xa8, 0x5a, 0xa1,
	0x37, 0xdd, 0x21, 0x2f, 0xc9, 0x79, 0x49, 0x06, 0xbb, 0xbe, 0xe3, 0x61, 0xaf, 0xf5, 0xf8, 0xd0,
	0x5e, 0x8a, 0x42, 0xf2, 0x88, 0x3d, 0xc3, 0x0f, 0xf1, 0xb0, 0xe5, 0xff, 0x00, 0x78, 0x76, 0x34,
	0xa0, 0x3b, 0x68, 0x72, 0xcd, 0x32, 0x85, 0x81, 0x67, 0x8c, 0xed, 0xd9, 0x3b, 0xff, 0x3f, 0x99,
	0xfd, 0x23, 0xec, 0xdf, 0x73, 0xc1, 0x96, 0x9a, 0x65, 0xc4, 0x2e, 0x89, 0x75, 0x00, 0xa6, 0x05,
	0x9c, 0xbd, 0x15, 0x36, 0x03, 0xdc, 0x03, 0x80, 0x56, 0x0b, 0x20, 0x0f, 0x9a, 0x9a, 0xeb, 0xb4,
	0x0d, 0x0e, 0x4b, 0x72, 0x96, 0x9b, 0x0e, 0xc0, 0x7b, 0x10, 0x36, 0x0d, 0xf4, 0x01, 0xda, 0x31,
	0x53, 0x51, 0xce, 0x37, 0x55, 0x50, 0xdc, 0xeb, 0x72, 0x2f, 0xf0, 0xbe, 0x17, 0x76, 0xdb, 0xc8,
	0x85, 0x03, 0x9a, 0x55, 0x4b, 0xc5, 0x86, 0x07, 0xc6, 0x06, 0xe9, 0x4d, 0x41, 0x78, 0x54, 0x90,
	0x0b, 0x0d, 0xb5, 0xde, 0xe2, 0x7e, 0x9d, 0xd6, 0x2a, 0x89, 0xb9, 0x33, 0xaa, 0xff, 0x54, 0xe2,
	0xe8, 0xe1, 0xb4, 0x9a, 0x7b, 0xae, 0x34, 0xba, 0x85, 0x16, 0x6f, 0x3e, 0xdb, 0xc0, 0xc3, 0xe7,
	0x02, 0xd7, 0xef, 0x39, 0x80, 0xbe, 0x05, 0x9c, 0x38, 0x3c, 0x39, 0xc9, 0x0a, 0xbe, 0x96, 0x79,
	0xd2, 0x31, 0x26, 0x4c, 0xfc, 0x33, 0x3f, 0xde, 0x24, 0x5c, 0xaf, 0xb6, 0x4f, 0x95, 0x12, 0xac,
	0xb9, 0x60, 0x91, 0x54, 0xbf, 0x94, 0x66, 0x59, 0x50, 0xc3, 0x13, 0xba, 0xe1, 0x41, 0xc2, 0x44,
	0x7d, 0x34, 0xc1, 0xe9, 0xf0, 0x6e, 0x9a, 0xea, 0x77, 0xcf, 0x5e, 0x7c, 0x21, 0x9f, 0xea, 0xfa,
	0xdb, 0xfc, 0x69, 0x50, 0x53, 0xf3, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xaf, 0x08, 0x7a, 0x20,
	0xa1, 0x02, 0x00, 0x00,
}
