// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account/v3/account_service.proto

package account

import (
	context "context"
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	v3 "github.com/kinecosystem/kin-api-internal/genproto/common/v3"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateAccountResponse_Result int32

const (
	CreateAccountResponse_OK     CreateAccountResponse_Result = 0
	CreateAccountResponse_EXISTS CreateAccountResponse_Result = 1
)

var CreateAccountResponse_Result_name = map[int32]string{
	0: "OK",
	1: "EXISTS",
}

var CreateAccountResponse_Result_value = map[string]int32{
	"OK":     0,
	"EXISTS": 1,
}

func (x CreateAccountResponse_Result) String() string {
	return proto.EnumName(CreateAccountResponse_Result_name, int32(x))
}

func (CreateAccountResponse_Result) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_eb584e8026f725ac, []int{2, 0}
}

type GetAccountInfoResponse_Result int32

const (
	GetAccountInfoResponse_OK        GetAccountInfoResponse_Result = 0
	GetAccountInfoResponse_NOT_FOUND GetAccountInfoResponse_Result = 1
)

var GetAccountInfoResponse_Result_name = map[int32]string{
	0: "OK",
	1: "NOT_FOUND",
}

var GetAccountInfoResponse_Result_value = map[string]int32{
	"OK":        0,
	"NOT_FOUND": 1,
}

func (x GetAccountInfoResponse_Result) String() string {
	return proto.EnumName(GetAccountInfoResponse_Result_name, int32(x))
}

func (GetAccountInfoResponse_Result) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_eb584e8026f725ac, []int{4, 0}
}

type AccountInfo struct {
	AccountId *v3.StellarAccountId `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// The last known sequence number of the account.
	SequenceNumber int64 `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	// The last known balance, in quarks, of the account.
	Balance              int64    `protobuf:"varint,3,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountInfo) Reset()         { *m = AccountInfo{} }
func (m *AccountInfo) String() string { return proto.CompactTextString(m) }
func (*AccountInfo) ProtoMessage()    {}
func (*AccountInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb584e8026f725ac, []int{0}
}

func (m *AccountInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountInfo.Unmarshal(m, b)
}
func (m *AccountInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountInfo.Marshal(b, m, deterministic)
}
func (m *AccountInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountInfo.Merge(m, src)
}
func (m *AccountInfo) XXX_Size() int {
	return xxx_messageInfo_AccountInfo.Size(m)
}
func (m *AccountInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AccountInfo proto.InternalMessageInfo

func (m *AccountInfo) GetAccountId() *v3.StellarAccountId {
	if m != nil {
		return m.AccountId
	}
	return nil
}

func (m *AccountInfo) GetSequenceNumber() int64 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

func (m *AccountInfo) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

type CreateAccountRequest struct {
	// Account to be created
	AccountId            *v3.StellarAccountId `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateAccountRequest) Reset()         { *m = CreateAccountRequest{} }
func (m *CreateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAccountRequest) ProtoMessage()    {}
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb584e8026f725ac, []int{1}
}

func (m *CreateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountRequest.Unmarshal(m, b)
}
func (m *CreateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountRequest.Marshal(b, m, deterministic)
}
func (m *CreateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountRequest.Merge(m, src)
}
func (m *CreateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAccountRequest.Size(m)
}
func (m *CreateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountRequest proto.InternalMessageInfo

func (m *CreateAccountRequest) GetAccountId() *v3.StellarAccountId {
	if m != nil {
		return m.AccountId
	}
	return nil
}

type CreateAccountResponse struct {
	Result CreateAccountResponse_Result `protobuf:"varint,1,opt,name=result,proto3,enum=kin.account.v3.CreateAccountResponse_Result" json:"result,omitempty"`
	// Will be present if the account was created or already existed.
	AccountInfo          *AccountInfo `protobuf:"bytes,2,opt,name=account_info,json=accountInfo,proto3" json:"account_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateAccountResponse) Reset()         { *m = CreateAccountResponse{} }
func (m *CreateAccountResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAccountResponse) ProtoMessage()    {}
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb584e8026f725ac, []int{2}
}

func (m *CreateAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountResponse.Unmarshal(m, b)
}
func (m *CreateAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountResponse.Marshal(b, m, deterministic)
}
func (m *CreateAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountResponse.Merge(m, src)
}
func (m *CreateAccountResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAccountResponse.Size(m)
}
func (m *CreateAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountResponse proto.InternalMessageInfo

func (m *CreateAccountResponse) GetResult() CreateAccountResponse_Result {
	if m != nil {
		return m.Result
	}
	return CreateAccountResponse_OK
}

func (m *CreateAccountResponse) GetAccountInfo() *AccountInfo {
	if m != nil {
		return m.AccountInfo
	}
	return nil
}

type GetAccountInfoRequest struct {
	AccountId            *v3.StellarAccountId `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetAccountInfoRequest) Reset()         { *m = GetAccountInfoRequest{} }
func (m *GetAccountInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountInfoRequest) ProtoMessage()    {}
func (*GetAccountInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb584e8026f725ac, []int{3}
}

func (m *GetAccountInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountInfoRequest.Unmarshal(m, b)
}
func (m *GetAccountInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetAccountInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountInfoRequest.Merge(m, src)
}
func (m *GetAccountInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountInfoRequest.Size(m)
}
func (m *GetAccountInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountInfoRequest proto.InternalMessageInfo

func (m *GetAccountInfoRequest) GetAccountId() *v3.StellarAccountId {
	if m != nil {
		return m.AccountId
	}
	return nil
}

type GetAccountInfoResponse struct {
	Result GetAccountInfoResponse_Result `protobuf:"varint,1,opt,name=result,proto3,enum=kin.account.v3.GetAccountInfoResponse_Result" json:"result,omitempty"`
	// Present iff result == Result::OK
	AccountInfo          *AccountInfo `protobuf:"bytes,2,opt,name=account_info,json=accountInfo,proto3" json:"account_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetAccountInfoResponse) Reset()         { *m = GetAccountInfoResponse{} }
func (m *GetAccountInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetAccountInfoResponse) ProtoMessage()    {}
func (*GetAccountInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb584e8026f725ac, []int{4}
}

func (m *GetAccountInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountInfoResponse.Unmarshal(m, b)
}
func (m *GetAccountInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetAccountInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountInfoResponse.Merge(m, src)
}
func (m *GetAccountInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetAccountInfoResponse.Size(m)
}
func (m *GetAccountInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountInfoResponse proto.InternalMessageInfo

func (m *GetAccountInfoResponse) GetResult() GetAccountInfoResponse_Result {
	if m != nil {
		return m.Result
	}
	return GetAccountInfoResponse_OK
}

func (m *GetAccountInfoResponse) GetAccountInfo() *AccountInfo {
	if m != nil {
		return m.AccountInfo
	}
	return nil
}

func init() {
	proto.RegisterEnum("kin.account.v3.CreateAccountResponse_Result", CreateAccountResponse_Result_name, CreateAccountResponse_Result_value)
	proto.RegisterEnum("kin.account.v3.GetAccountInfoResponse_Result", GetAccountInfoResponse_Result_name, GetAccountInfoResponse_Result_value)
	proto.RegisterType((*AccountInfo)(nil), "kin.account.v3.AccountInfo")
	proto.RegisterType((*CreateAccountRequest)(nil), "kin.account.v3.CreateAccountRequest")
	proto.RegisterType((*CreateAccountResponse)(nil), "kin.account.v3.CreateAccountResponse")
	proto.RegisterType((*GetAccountInfoRequest)(nil), "kin.account.v3.GetAccountInfoRequest")
	proto.RegisterType((*GetAccountInfoResponse)(nil), "kin.account.v3.GetAccountInfoResponse")
}

func init() { proto.RegisterFile("account/v3/account_service.proto", fileDescriptor_eb584e8026f725ac) }

var fileDescriptor_eb584e8026f725ac = []byte{
	// 464 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0x51, 0x6b, 0x13, 0x41,
	0x10, 0xc7, 0xdd, 0x14, 0xaf, 0x76, 0x62, 0x63, 0x58, 0x4c, 0x0d, 0x51, 0x68, 0x38, 0xac, 0xf6,
	0xc1, 0xec, 0x41, 0xf2, 0x28, 0x08, 0xc6, 0x54, 0x2d, 0x42, 0x02, 0x97, 0x0a, 0x22, 0x62, 0xdc,
	0x5c, 0xa6, 0xf1, 0xe8, 0x65, 0x37, 0xee, 0xee, 0x1d, 0xf8, 0x15, 0xfc, 0x08, 0x7e, 0x15, 0x5f,
	0x7c, 0xf4, 0x33, 0xf9, 0x24, 0xb7, 0x77, 0x67, 0x93, 0x6b, 0xa1, 0x79, 0xc8, 0xdb, 0xcc, 0xec,
	0xfc, 0x66, 0x76, 0xff, 0x7f, 0xee, 0xa0, 0xcd, 0x83, 0x40, 0xc6, 0xc2, 0x78, 0x49, 0xcf, 0xcb,
	0xc3, 0x89, 0x46, 0x95, 0x84, 0x01, 0xb2, 0xa5, 0x92, 0x46, 0xd2, 0xda, 0x45, 0x28, 0x58, 0x7e,
	0xc4, 0x92, 0x5e, 0xeb, 0x41, 0xc2, 0xa3, 0x70, 0xc6, 0x0d, 0x7a, 0x45, 0x90, 0x35, 0xb6, 0x1a,
	0x81, 0x5c, 0x2c, 0xa4, 0x48, 0x27, 0x2d, 0xe4, 0x0c, 0xa3, 0xac, 0xec, 0xfe, 0x24, 0x50, 0x7d,
	0x99, 0xe1, 0xa7, 0xe2, 0x5c, 0xd2, 0xb7, 0x00, 0xc5, 0xa2, 0x70, 0xd6, 0x24, 0x6d, 0x72, 0x5c,
	0xed, 0x1e, 0xb2, 0x74, 0x49, 0xc6, 0xb3, 0xa4, 0xc7, 0xc6, 0x06, 0xa3, 0x88, 0xab, 0x02, 0x9b,
	0xf5, 0xef, 0xfc, 0xed, 0xdf, 0xfe, 0x41, 0x2a, 0x75, 0xe2, 0xef, 0xf1, 0xa2, 0x48, 0x9f, 0xc2,
	0x3d, 0x8d, 0xdf, 0x62, 0x14, 0x01, 0x4e, 0x44, 0xbc, 0x98, 0xa2, 0x6a, 0x56, 0xda, 0xe4, 0x78,
	0xc7, 0xaf, 0x15, 0xe5, 0xa1, 0xad, 0xd2, 0x26, 0xec, 0x4e, 0x79, 0xc4, 0x45, 0x80, 0xcd, 0x1d,
	0xdb, 0x50, 0xa4, 0xee, 0x17, 0xb8, 0xff, 0x4a, 0x21, 0x37, 0x98, 0xaf, 0xf2, 0x53, 0x50, 0x9b,
	0xed, 0x5d, 0xd2, 0xfd, 0x45, 0xa0, 0x51, 0x5a, 0xa1, 0x97, 0x52, 0x68, 0xa4, 0x03, 0x70, 0x14,
	0xea, 0x38, 0x32, 0x76, 0x7e, 0xad, 0xfb, 0x8c, 0xad, 0x2b, 0xcd, 0xae, 0xc5, 0x98, 0x6f, 0x19,
	0x3f, 0x67, 0xe9, 0x0b, 0xb8, 0xfb, 0xff, 0xa6, 0xe2, 0x5c, 0x5a, 0x05, 0xaa, 0xdd, 0x87, 0xe5,
	0x59, 0x2b, 0x0e, 0xf8, 0x55, 0x7e, 0x99, 0xb8, 0x8f, 0xc0, 0xc9, 0x26, 0x52, 0x07, 0x2a, 0xa3,
	0x77, 0xf5, 0x5b, 0x14, 0xc0, 0x39, 0xf9, 0x70, 0x3a, 0x3e, 0x1b, 0xd7, 0x89, 0xcb, 0xa1, 0xf1,
	0x06, 0xcd, 0x2a, 0xbc, 0x75, 0x81, 0x7e, 0x13, 0x38, 0x28, 0xef, 0xc8, 0x15, 0x3a, 0x29, 0x29,
	0xd4, 0x29, 0xbf, 0xea, 0x7a, 0x6e, 0xdb, 0x12, 0x1d, 0x5e, 0x91, 0x68, 0x1f, 0xf6, 0x86, 0xa3,
	0xb3, 0xc9, 0xeb, 0xd1, 0xfb, 0xe1, 0xa0, 0x4e, 0xba, 0x7f, 0x08, 0xec, 0xe6, 0x34, 0xfd, 0x04,
	0xfb, 0x6b, 0xbe, 0xd1, 0xc7, 0x37, 0xd8, 0x6a, 0xf5, 0x6c, 0x1d, 0x6d, 0x64, 0x3e, 0x9d, 0x40,
	0x6d, 0xfd, 0xcd, 0xf4, 0xe8, 0x26, 0x4d, 0xb2, 0xf9, 0x4f, 0x36, 0x93, 0xae, 0xff, 0x19, 0x0e,
	0xa4, 0x9a, 0xdb, 0xe6, 0x39, 0xae, 0x02, 0x1f, 0x07, 0xf3, 0xd0, 0x7c, 0x8d, 0xa7, 0xa9, 0xbf,
	0xde, 0x45, 0x28, 0x30, 0x90, 0xfa, 0xbb, 0x36, 0x68, 0x93, 0x0e, 0x5f, 0x86, 0x9d, 0x50, 0x18,
	0x54, 0x82, 0x47, 0xde, 0x1c, 0x85, 0xfd, 0xf4, 0xbd, 0xcb, 0x7f, 0xcb, 0xf3, 0x3c, 0x9c, 0x3a,
	0xf6, 0xa4, 0xf7, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xe9, 0xc7, 0x5e, 0xb0, 0x78, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountClient is the client API for Account service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountClient interface {
	// CreateAccount creates an account using a seed account configured
	// by the service.
	CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error)
	// GetAccountInfo returns the balance of a specified account.
	GetAccountInfo(ctx context.Context, in *GetAccountInfoRequest, opts ...grpc.CallOption) (*GetAccountInfoResponse, error)
}

type accountClient struct {
	cc *grpc.ClientConn
}

func NewAccountClient(cc *grpc.ClientConn) AccountClient {
	return &accountClient{cc}
}

func (c *accountClient) CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error) {
	out := new(CreateAccountResponse)
	err := c.cc.Invoke(ctx, "/kin.account.v3.Account/CreateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) GetAccountInfo(ctx context.Context, in *GetAccountInfoRequest, opts ...grpc.CallOption) (*GetAccountInfoResponse, error) {
	out := new(GetAccountInfoResponse)
	err := c.cc.Invoke(ctx, "/kin.account.v3.Account/GetAccountInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServer is the server API for Account service.
type AccountServer interface {
	// CreateAccount creates an account using a seed account configured
	// by the service.
	CreateAccount(context.Context, *CreateAccountRequest) (*CreateAccountResponse, error)
	// GetAccountInfo returns the balance of a specified account.
	GetAccountInfo(context.Context, *GetAccountInfoRequest) (*GetAccountInfoResponse, error)
}

// UnimplementedAccountServer can be embedded to have forward compatible implementations.
type UnimplementedAccountServer struct {
}

func (*UnimplementedAccountServer) CreateAccount(ctx context.Context, req *CreateAccountRequest) (*CreateAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAccount not implemented")
}
func (*UnimplementedAccountServer) GetAccountInfo(ctx context.Context, req *GetAccountInfoRequest) (*GetAccountInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountInfo not implemented")
}

func RegisterAccountServer(s *grpc.Server, srv AccountServer) {
	s.RegisterService(&_Account_serviceDesc, srv)
}

func _Account_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kin.account.v3.Account/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).CreateAccount(ctx, req.(*CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_GetAccountInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).GetAccountInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kin.account.v3.Account/GetAccountInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).GetAccountInfo(ctx, req.(*GetAccountInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Account_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kin.account.v3.Account",
	HandlerType: (*AccountServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccount",
			Handler:    _Account_CreateAccount_Handler,
		},
		{
			MethodName: "GetAccountInfo",
			Handler:    _Account_GetAccountInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account/v3/account_service.proto",
}
