// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account/v3/account_service.proto

package account

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	v3 "github.com/kinecosystem/kin-api/genproto/common/v3"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateAccountResponse_Result int32

const (
	CreateAccountResponse_OK     CreateAccountResponse_Result = 0
	CreateAccountResponse_EXISTS CreateAccountResponse_Result = 1
)

var CreateAccountResponse_Result_name = map[int32]string{
	0: "OK",
	1: "EXISTS",
}

var CreateAccountResponse_Result_value = map[string]int32{
	"OK":     0,
	"EXISTS": 1,
}

func (x CreateAccountResponse_Result) String() string {
	return proto.EnumName(CreateAccountResponse_Result_name, int32(x))
}

func (CreateAccountResponse_Result) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_eb584e8026f725ac, []int{1, 0}
}

type CreateAccountRequest struct {
	// Account to be created
	AccountId            *v3.StellarAccountId `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateAccountRequest) Reset()         { *m = CreateAccountRequest{} }
func (m *CreateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAccountRequest) ProtoMessage()    {}
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb584e8026f725ac, []int{0}
}

func (m *CreateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountRequest.Unmarshal(m, b)
}
func (m *CreateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountRequest.Marshal(b, m, deterministic)
}
func (m *CreateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountRequest.Merge(m, src)
}
func (m *CreateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAccountRequest.Size(m)
}
func (m *CreateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountRequest proto.InternalMessageInfo

func (m *CreateAccountRequest) GetAccountId() *v3.StellarAccountId {
	if m != nil {
		return m.AccountId
	}
	return nil
}

type CreateAccountResponse struct {
	Result               CreateAccountResponse_Result `protobuf:"varint,1,opt,name=result,proto3,enum=kin.account.v3.CreateAccountResponse_Result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *CreateAccountResponse) Reset()         { *m = CreateAccountResponse{} }
func (m *CreateAccountResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAccountResponse) ProtoMessage()    {}
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb584e8026f725ac, []int{1}
}

func (m *CreateAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountResponse.Unmarshal(m, b)
}
func (m *CreateAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountResponse.Marshal(b, m, deterministic)
}
func (m *CreateAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountResponse.Merge(m, src)
}
func (m *CreateAccountResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAccountResponse.Size(m)
}
func (m *CreateAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountResponse proto.InternalMessageInfo

func (m *CreateAccountResponse) GetResult() CreateAccountResponse_Result {
	if m != nil {
		return m.Result
	}
	return CreateAccountResponse_OK
}

func init() {
	proto.RegisterEnum("kin.account.v3.CreateAccountResponse_Result", CreateAccountResponse_Result_name, CreateAccountResponse_Result_value)
	proto.RegisterType((*CreateAccountRequest)(nil), "kin.account.v3.CreateAccountRequest")
	proto.RegisterType((*CreateAccountResponse)(nil), "kin.account.v3.CreateAccountResponse")
}

func init() { proto.RegisterFile("account/v3/account_service.proto", fileDescriptor_eb584e8026f725ac) }

var fileDescriptor_eb584e8026f725ac = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x51, 0x5f, 0x4b, 0xfb, 0x30,
	0x14, 0xfd, 0x75, 0xf0, 0xab, 0x7a, 0xc5, 0x31, 0x82, 0x53, 0x19, 0x82, 0x63, 0x28, 0xf8, 0xa0,
	0x09, 0xac, 0x8f, 0x7b, 0x72, 0x2a, 0x38, 0x7c, 0x10, 0x3a, 0x05, 0x11, 0x41, 0xb3, 0xf6, 0x52,
	0xc3, 0xba, 0x64, 0x26, 0x69, 0x41, 0xfc, 0x06, 0x7e, 0x64, 0x9f, 0x64, 0x69, 0x8a, 0x4e, 0x04,
	0x7d, 0x3b, 0x3d, 0xf7, 0xfc, 0x69, 0xee, 0x85, 0x2e, 0x4f, 0x12, 0x55, 0x48, 0xcb, 0xca, 0x88,
	0x79, 0xf8, 0x60, 0x50, 0x97, 0x22, 0x41, 0x3a, 0xd7, 0xca, 0x2a, 0xd2, 0x9c, 0x0a, 0x49, 0xfd,
	0x88, 0x96, 0x51, 0x67, 0xbb, 0xe4, 0xb9, 0x48, 0xb9, 0x45, 0x56, 0x83, 0x4a, 0xd8, 0x69, 0x27,
	0x6a, 0x36, 0x53, 0x72, 0x91, 0x34, 0x53, 0x29, 0xe6, 0x15, 0xdd, 0x7b, 0x84, 0xcd, 0x53, 0x8d,
	0xdc, 0xe2, 0x49, 0x95, 0x11, 0xe3, 0x73, 0x81, 0xc6, 0x92, 0x0b, 0x80, 0xba, 0x50, 0xa4, 0x3b,
	0x41, 0x37, 0x38, 0x5c, 0xef, 0xef, 0xd1, 0x45, 0x59, 0x95, 0x43, 0xcb, 0x88, 0x8e, 0x2d, 0xe6,
	0x39, 0xd7, 0xde, 0x39, 0x4a, 0x87, 0xab, 0xef, 0xc3, 0xff, 0x6f, 0x41, 0xa3, 0x15, 0xc4, 0x6b,
	0xbc, 0x26, 0x7b, 0xaf, 0xd0, 0xfe, 0xd6, 0x60, 0xe6, 0x4a, 0x1a, 0x24, 0x67, 0x10, 0x6a, 0x34,
	0x45, 0x6e, 0x5d, 0x7c, 0xb3, 0x7f, 0x44, 0x97, 0xdf, 0x42, 0x7f, 0xb4, 0xd1, 0xd8, 0x79, 0x62,
	0xef, 0xed, 0xed, 0x42, 0x58, 0x31, 0x24, 0x84, 0xc6, 0xd5, 0x65, 0xeb, 0x1f, 0x01, 0x08, 0xcf,
	0x6f, 0x47, 0xe3, 0xeb, 0x71, 0x2b, 0xe8, 0x67, 0xb0, 0xe2, 0xfd, 0xe4, 0x1e, 0x36, 0x96, 0x02,
	0xc9, 0xfe, 0x2f, 0x7d, 0x6e, 0x11, 0x9d, 0x83, 0x3f, 0xfd, 0xd5, 0xf0, 0x06, 0xb6, 0x94, 0xce,
	0x9c, 0x36, 0xc3, 0xaf, 0xfa, 0xbb, 0x41, 0x26, 0xec, 0x53, 0x31, 0x59, 0xec, 0x8d, 0x4d, 0x85,
	0xc4, 0x44, 0x99, 0x17, 0x63, 0xd1, 0x7d, 0x1c, 0xf3, 0xb9, 0x60, 0x19, 0x4a, 0x77, 0x0b, 0xf6,
	0x79, 0xec, 0x81, 0x87, 0x93, 0xd0, 0x4d, 0xa2, 0x8f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9b, 0xcc,
	0xef, 0xcb, 0x09, 0x02, 0x00, 0x00,
}
