// Code generated by protoc-gen-go. DO NOT EDIT.
// source: offer/v3/offer_service.proto

package offer

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetOffersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOffersRequest) Reset()         { *m = GetOffersRequest{} }
func (m *GetOffersRequest) String() string { return proto.CompactTextString(m) }
func (*GetOffersRequest) ProtoMessage()    {}
func (*GetOffersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8927836b16a2e50f, []int{0}
}

func (m *GetOffersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOffersRequest.Unmarshal(m, b)
}
func (m *GetOffersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOffersRequest.Marshal(b, m, deterministic)
}
func (m *GetOffersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOffersRequest.Merge(m, src)
}
func (m *GetOffersRequest) XXX_Size() int {
	return xxx_messageInfo_GetOffersRequest.Size(m)
}
func (m *GetOffersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOffersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOffersRequest proto.InternalMessageInfo

type GetOffersResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOffersResponse) Reset()         { *m = GetOffersResponse{} }
func (m *GetOffersResponse) String() string { return proto.CompactTextString(m) }
func (*GetOffersResponse) ProtoMessage()    {}
func (*GetOffersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8927836b16a2e50f, []int{1}
}

func (m *GetOffersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOffersResponse.Unmarshal(m, b)
}
func (m *GetOffersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOffersResponse.Marshal(b, m, deterministic)
}
func (m *GetOffersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOffersResponse.Merge(m, src)
}
func (m *GetOffersResponse) XXX_Size() int {
	return xxx_messageInfo_GetOffersResponse.Size(m)
}
func (m *GetOffersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOffersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOffersResponse proto.InternalMessageInfo

type ClaimOfferRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClaimOfferRequest) Reset()         { *m = ClaimOfferRequest{} }
func (m *ClaimOfferRequest) String() string { return proto.CompactTextString(m) }
func (*ClaimOfferRequest) ProtoMessage()    {}
func (*ClaimOfferRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8927836b16a2e50f, []int{2}
}

func (m *ClaimOfferRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClaimOfferRequest.Unmarshal(m, b)
}
func (m *ClaimOfferRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClaimOfferRequest.Marshal(b, m, deterministic)
}
func (m *ClaimOfferRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClaimOfferRequest.Merge(m, src)
}
func (m *ClaimOfferRequest) XXX_Size() int {
	return xxx_messageInfo_ClaimOfferRequest.Size(m)
}
func (m *ClaimOfferRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClaimOfferRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClaimOfferRequest proto.InternalMessageInfo

type ClaimOfferResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClaimOfferResponse) Reset()         { *m = ClaimOfferResponse{} }
func (m *ClaimOfferResponse) String() string { return proto.CompactTextString(m) }
func (*ClaimOfferResponse) ProtoMessage()    {}
func (*ClaimOfferResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8927836b16a2e50f, []int{3}
}

func (m *ClaimOfferResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClaimOfferResponse.Unmarshal(m, b)
}
func (m *ClaimOfferResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClaimOfferResponse.Marshal(b, m, deterministic)
}
func (m *ClaimOfferResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClaimOfferResponse.Merge(m, src)
}
func (m *ClaimOfferResponse) XXX_Size() int {
	return xxx_messageInfo_ClaimOfferResponse.Size(m)
}
func (m *ClaimOfferResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClaimOfferResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClaimOfferResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GetOffersRequest)(nil), "kin.offer.v3.GetOffersRequest")
	proto.RegisterType((*GetOffersResponse)(nil), "kin.offer.v3.GetOffersResponse")
	proto.RegisterType((*ClaimOfferRequest)(nil), "kin.offer.v3.ClaimOfferRequest")
	proto.RegisterType((*ClaimOfferResponse)(nil), "kin.offer.v3.ClaimOfferResponse")
}

func init() { proto.RegisterFile("offer/v3/offer_service.proto", fileDescriptor_8927836b16a2e50f) }

var fileDescriptor_8927836b16a2e50f = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xc9, 0x4f, 0x4b, 0x4b,
	0x2d, 0xd2, 0x2f, 0x33, 0xd6, 0x07, 0x33, 0xe2, 0x8b, 0x53, 0x8b, 0xca, 0x32, 0x93, 0x53, 0xf5,
	0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x78, 0xb2, 0x33, 0xf3, 0xf4, 0xc0, 0x12, 0x7a, 0x65, 0xc6,
	0x4a, 0x42, 0x5c, 0x02, 0xee, 0xa9, 0x25, 0xfe, 0x20, 0x6e, 0x71, 0x50, 0x6a, 0x61, 0x69, 0x6a,
	0x71, 0x89, 0x92, 0x30, 0x97, 0x20, 0x92, 0x58, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0x2a, 0x48, 0xd0,
	0x39, 0x27, 0x31, 0x33, 0x17, 0x2c, 0x0c, 0x53, 0x29, 0xc2, 0x25, 0x84, 0x2c, 0x08, 0x51, 0x6a,
	0xb4, 0x8c, 0x91, 0x8b, 0x15, 0x2c, 0x22, 0xe4, 0xc3, 0xc5, 0x09, 0x37, 0x49, 0x48, 0x4e, 0x0f,
	0xd9, 0x66, 0x3d, 0x74, 0x6b, 0xa5, 0xe4, 0x71, 0xca, 0x43, 0xcc, 0x15, 0xf2, 0xe7, 0xe2, 0x42,
	0xd8, 0x26, 0x84, 0xa6, 0x1c, 0xc3, 0x71, 0x52, 0x0a, 0xb8, 0x15, 0x40, 0x0c, 0x74, 0x8a, 0xe0,
	0x12, 0xc9, 0x2f, 0x4a, 0x07, 0x2b, 0x4b, 0x4f, 0x45, 0x28, 0x8d, 0x72, 0x48, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0xcf, 0xce, 0xcc, 0x4b, 0x4d, 0xce, 0x2f, 0xae, 0x2c,
	0x2e, 0x49, 0x05, 0x73, 0x74, 0x13, 0x0b, 0x32, 0x75, 0x33, 0xf3, 0x4a, 0x52, 0x8b, 0xf2, 0x12,
	0x73, 0xf4, 0xd3, 0x53, 0xf3, 0xc0, 0xa1, 0xaa, 0x0f, 0x0b, 0x72, 0x6b, 0x30, 0x23, 0x89, 0x0d,
	0x2c, 0x6a, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xa9, 0x68, 0x19, 0x94, 0x8b, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OfferClient is the client API for Offer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OfferClient interface {
	// todo
	GetOffers(ctx context.Context, in *GetOffersRequest, opts ...grpc.CallOption) (*GetOffersResponse, error)
	// todo
	ClaimOffer(ctx context.Context, in *ClaimOfferRequest, opts ...grpc.CallOption) (*ClaimOfferResponse, error)
}

type offerClient struct {
	cc *grpc.ClientConn
}

func NewOfferClient(cc *grpc.ClientConn) OfferClient {
	return &offerClient{cc}
}

func (c *offerClient) GetOffers(ctx context.Context, in *GetOffersRequest, opts ...grpc.CallOption) (*GetOffersResponse, error) {
	out := new(GetOffersResponse)
	err := c.cc.Invoke(ctx, "/kin.offer.v3.Offer/GetOffers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *offerClient) ClaimOffer(ctx context.Context, in *ClaimOfferRequest, opts ...grpc.CallOption) (*ClaimOfferResponse, error) {
	out := new(ClaimOfferResponse)
	err := c.cc.Invoke(ctx, "/kin.offer.v3.Offer/ClaimOffer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OfferServer is the server API for Offer service.
type OfferServer interface {
	// todo
	GetOffers(context.Context, *GetOffersRequest) (*GetOffersResponse, error)
	// todo
	ClaimOffer(context.Context, *ClaimOfferRequest) (*ClaimOfferResponse, error)
}

// UnimplementedOfferServer can be embedded to have forward compatible implementations.
type UnimplementedOfferServer struct {
}

func (*UnimplementedOfferServer) GetOffers(ctx context.Context, req *GetOffersRequest) (*GetOffersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOffers not implemented")
}
func (*UnimplementedOfferServer) ClaimOffer(ctx context.Context, req *ClaimOfferRequest) (*ClaimOfferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimOffer not implemented")
}

func RegisterOfferServer(s *grpc.Server, srv OfferServer) {
	s.RegisterService(&_Offer_serviceDesc, srv)
}

func _Offer_GetOffers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOffersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfferServer).GetOffers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kin.offer.v3.Offer/GetOffers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfferServer).GetOffers(ctx, req.(*GetOffersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Offer_ClaimOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimOfferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfferServer).ClaimOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kin.offer.v3.Offer/ClaimOffer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfferServer).ClaimOffer(ctx, req.(*ClaimOfferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Offer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kin.offer.v3.Offer",
	HandlerType: (*OfferServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOffers",
			Handler:    _Offer_GetOffers_Handler,
		},
		{
			MethodName: "ClaimOffer",
			Handler:    _Offer_ClaimOffer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "offer/v3/offer_service.proto",
}
