// Code generated by protoc-gen-go. DO NOT EDIT.
// source: metrics/v3/ingestion_service.proto

package metrics

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SubmitResponse_Result int32

const (
	SubmitResponse_OK SubmitResponse_Result = 0
)

var SubmitResponse_Result_name = map[int32]string{
	0: "OK",
}

var SubmitResponse_Result_value = map[string]int32{
	"OK": 0,
}

func (x SubmitResponse_Result) String() string {
	return proto.EnumName(SubmitResponse_Result_name, int32(x))
}

func (SubmitResponse_Result) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_914678a26d61e0c1, []int{1, 0}
}

type SubmitRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitRequest) Reset()         { *m = SubmitRequest{} }
func (m *SubmitRequest) String() string { return proto.CompactTextString(m) }
func (*SubmitRequest) ProtoMessage()    {}
func (*SubmitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_914678a26d61e0c1, []int{0}
}

func (m *SubmitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitRequest.Unmarshal(m, b)
}
func (m *SubmitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitRequest.Marshal(b, m, deterministic)
}
func (m *SubmitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitRequest.Merge(m, src)
}
func (m *SubmitRequest) XXX_Size() int {
	return xxx_messageInfo_SubmitRequest.Size(m)
}
func (m *SubmitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitRequest proto.InternalMessageInfo

type SubmitResponse struct {
	Result               SubmitResponse_Result `protobuf:"varint,1,opt,name=result,proto3,enum=kin.metrics.v3.SubmitResponse_Result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *SubmitResponse) Reset()         { *m = SubmitResponse{} }
func (m *SubmitResponse) String() string { return proto.CompactTextString(m) }
func (*SubmitResponse) ProtoMessage()    {}
func (*SubmitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_914678a26d61e0c1, []int{1}
}

func (m *SubmitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitResponse.Unmarshal(m, b)
}
func (m *SubmitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitResponse.Marshal(b, m, deterministic)
}
func (m *SubmitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitResponse.Merge(m, src)
}
func (m *SubmitResponse) XXX_Size() int {
	return xxx_messageInfo_SubmitResponse.Size(m)
}
func (m *SubmitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitResponse proto.InternalMessageInfo

func (m *SubmitResponse) GetResult() SubmitResponse_Result {
	if m != nil {
		return m.Result
	}
	return SubmitResponse_OK
}

func init() {
	proto.RegisterEnum("kin.metrics.v3.SubmitResponse_Result", SubmitResponse_Result_name, SubmitResponse_Result_value)
	proto.RegisterType((*SubmitRequest)(nil), "kin.metrics.v3.SubmitRequest")
	proto.RegisterType((*SubmitResponse)(nil), "kin.metrics.v3.SubmitResponse")
}

func init() { proto.RegisterFile("metrics/v3/ingestion_service.proto", fileDescriptor_914678a26d61e0c1) }

var fileDescriptor_914678a26d61e0c1 = []byte{
	// 228 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x31, 0x4b, 0x04, 0x31,
	0x10, 0x85, 0x3d, 0x8b, 0x80, 0x03, 0xae, 0x47, 0x0a, 0x11, 0x41, 0x91, 0x05, 0xc1, 0xc6, 0x04,
	0x6e, 0xcb, 0xc3, 0xc6, 0x46, 0xc4, 0x42, 0x58, 0xb5, 0xb1, 0x91, 0xdb, 0x30, 0xc4, 0xe1, 0xdc,
	0x64, 0xcd, 0x4c, 0x16, 0xfc, 0xf7, 0x42, 0x6e, 0x0f, 0xbd, 0x42, 0xbb, 0xe4, 0xe5, 0x7b, 0x2f,
	0x8f, 0x07, 0x75, 0x8f, 0x92, 0xc8, 0xb1, 0x1d, 0x1b, 0x4b, 0xc1, 0x23, 0x0b, 0xc5, 0xf0, 0xc6,
	0x98, 0x46, 0x72, 0x68, 0x86, 0x14, 0x25, 0xea, 0x6a, 0x4d, 0xc1, 0x4c, 0x9c, 0x19, 0x9b, 0xfa,
	0x08, 0x0e, 0x9f, 0x72, 0xd7, 0x93, 0xb4, 0xf8, 0x99, 0x91, 0xa5, 0x5e, 0x41, 0xb5, 0x15, 0x78,
	0x88, 0x81, 0x51, 0xdf, 0x80, 0x4a, 0xc8, 0xf9, 0x43, 0x4e, 0x66, 0x17, 0xb3, 0xab, 0x6a, 0x71,
	0x69, 0x76, 0x33, 0xcc, 0x2e, 0x6f, 0xda, 0x02, 0xb7, 0x93, 0xa9, 0x9e, 0x83, 0xda, 0x28, 0x5a,
	0xc1, 0xfe, 0xe3, 0xc3, 0x7c, 0x6f, 0xf1, 0x0c, 0x07, 0xf7, 0xdb, 0x7a, 0xfa, 0x0e, 0xd4, 0xc6,
	0xaf, 0xcf, 0xfe, 0xca, 0x2d, 0xc5, 0x4e, 0xcf, 0xff, 0xff, 0xf6, 0xf6, 0x05, 0x8e, 0x63, 0xf2,
	0x05, 0xf2, 0xf8, 0x1b, 0x7c, 0x5d, 0x7a, 0x92, 0xf7, 0xdc, 0x19, 0x17, 0x7b, 0xbb, 0xa6, 0x80,
	0x2e, 0xf2, 0x17, 0x0b, 0x96, 0xcb, 0xf5, 0x6a, 0x20, 0xeb, 0x31, 0x94, 0x75, 0xec, 0xcf, 0x80,
	0xcb, 0xe9, 0xd8, 0xa9, 0xf2, 0xd2, 0x7c, 0x07, 0x00, 0x00, 0xff, 0xff, 0x02, 0x62, 0xaf, 0x62,
	0x5d, 0x01, 0x00, 0x00,
}
